  [package]
    name = "cli_project"
    version = "0.1.0"
    edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

   [dependencies]

    whoami = "1.5.1"
    walkdir = "2.5.0"
filesize = "0.2.0"
chrono = "0.4"
